// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelProject.Data;

#nullable disable

namespace ModelProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918144503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelProject.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("FacilityId");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetCode = "AC-1001",
                            AssetType = "Compressor",
                            FacilityId = 1,
                            Name = "Air Compressor #1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            AssetCode = "CV-1002",
                            AssetType = "Conveyor",
                            FacilityId = 1,
                            Name = "Conveyor Belt A",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            AssetCode = "HV-2001",
                            AssetType = "HVAC",
                            FacilityId = 2,
                            Name = "HVAC Unit 3",
                            Status = "UnderMaintenance"
                        },
                        new
                        {
                            Id = 4,
                            AssetCode = "FL-3001",
                            AssetType = "Vehicle",
                            FacilityId = 3,
                            Name = "Forklift 7",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ModelProject.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acme Manufacturing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Northwind Logistics"
                        });
                });

            modelBuilder.Entity("ModelProject.Entities.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Facilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Location = "Chennai, IN",
                            Name = "Acme Plant 1"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            Location = "Coimbatore, IN",
                            Name = "Acme Plant 2"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 2,
                            Location = "Bengaluru, IN",
                            Name = "Northwind Warehouse A"
                        });
                });

            modelBuilder.Entity("ModelProject.Entities.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Technicians", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "arun.kumar@example.com",
                            IsActive = true,
                            Name = "Arun Kumar"
                        },
                        new
                        {
                            Id = 2,
                            Email = "priya.sharma@example.com",
                            IsActive = true,
                            Name = "Priya Sharma"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ravi.verma@example.com",
                            IsActive = true,
                            Name = "Ravi Verma"
                        });
                });

            modelBuilder.Entity("ModelProject.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTechnicianId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedTechnicianId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("FacilityId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_WorkOrders_FacilityId_Status_CreatedAt");

                    b.ToTable("WorkOrders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pressure drops below threshold after 20 minutes of operation.",
                            FacilityId = 1,
                            Priority = "High",
                            RowVersion = new byte[0],
                            Status = "New",
                            Title = "Compressor pressure drop",
                            UpdatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            AssignedTechnicianId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Belt drifts to one side under load.",
                            FacilityId = 1,
                            Priority = "Medium",
                            RowVersion = new byte[0],
                            Status = "Assigned",
                            Title = "Conveyor belt misalignment",
                            UpdatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 3,
                            AssignedTechnicianId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unit runs continuously without reaching the set temperature.",
                            FacilityId = 2,
                            Priority = "Critical",
                            RowVersion = new byte[0],
                            Status = "InProgress",
                            Title = "HVAC unit not cooling",
                            UpdatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ModelProject.Entities.WorkOrderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId", "ChangedAt");

                    b.ToTable("WorkOrderHistories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ChangedBy = "system.seed",
                            Comments = "Assigned to Arun Kumar.",
                            NewStatus = "Assigned",
                            OldStatus = "New",
                            WorkOrderId = 2
                        },
                        new
                        {
                            Id = 2,
                            ChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ChangedBy = "system.seed",
                            Comments = "Assigned to Priya Sharma.",
                            NewStatus = "Assigned",
                            OldStatus = "New",
                            WorkOrderId = 3
                        },
                        new
                        {
                            Id = 3,
                            ChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ChangedBy = "system.seed",
                            Comments = "Technician started work.",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned",
                            WorkOrderId = 3
                        });
                });

            modelBuilder.Entity("ModelProject.Entities.Asset", b =>
                {
                    b.HasOne("ModelProject.Entities.Facility", "Facility")
                        .WithMany("Assets")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("ModelProject.Entities.Facility", b =>
                {
                    b.HasOne("ModelProject.Entities.Customer", "Customer")
                        .WithMany("Facilities")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ModelProject.Entities.WorkOrder", b =>
                {
                    b.HasOne("ModelProject.Entities.Asset", "Asset")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelProject.Entities.Technician", "AssignedTechnician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ModelProject.Entities.Facility", "Facility")
                        .WithMany("WorkOrders")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("ModelProject.Entities.WorkOrderHistory", b =>
                {
                    b.HasOne("ModelProject.Entities.WorkOrder", "WorkOrder")
                        .WithMany("History")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ModelProject.Entities.Asset", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ModelProject.Entities.Customer", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("ModelProject.Entities.Facility", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ModelProject.Entities.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ModelProject.Entities.WorkOrder", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
